### ISSUE TITLE
Join the Strike Page Submit button is not responding

### ISSUE THREAD

**Issue by Ampdx** [debtcollective/debtcollective-web#62]
I'm attempting to sign up to Join The Strike against Everest Colleges as one of the victims that fell prey to Everest college. After I enter all my information on the Join the Strike Information Sign Up page, I click submit and I get no response from the web page. The page does not take me to a confirmation page, nothing happens when I click submit. I enter all my information correctly into each individual field on the Join the Strike Information Sign Up page, and still no response with the submit button. I would Really like to be one of the members who have joined the strike against Everest College, but the sign up page is non responsive and not accepting my submission, I get no response from the page when I click Submit. Please fix this and let me know when I'm able to sign up using the Join the Strike Sign Up page: https://debtcollective.org/studentstrike

Thank You,

Alicia Morris

**Comment by karissa** [comment]
Hey Alicia,

Does it work for you now? Could you possibly send me your contact info and we will have someone reach out to you? I'm Karissa McKelvey on Facebook.
